name:                haskell-helloword
version:             0.1.0.0
github:              "bykclk/haskell-helloword"
license:             BSD3
author:              "Ömer Büyükçelik"
maintainer:          "omerbuyukcelik@gmail.com"
copyright:           "2020 Ömer Büyükçelik"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bykclk/haskell-helloword#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  haskell-helloword-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-helloword

tests:
  haskell-helloword-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-helloword
    - hspec
